// Manual selector-এ দেখানোর জন্য দেশের লিস্ট।
// প্রতিটা দেশের সাথে default language আর currency বাঁধা আছে।
// user চাইলে language/currency আলাদাভাবেও বদলাতে পারবে (LocaleSwitcher দেখো)।
export const countries = [
  { code: "US", name: "United States", lang: "en", currency: "USD" },
  { code: "GB", name: "United Kingdom", lang: "en", currency: "GBP" },
  { code: "CA", name: "Canada", lang: "en", currency: "CAD" },
  { code: "AU", name: "Australia", lang: "en", currency: "AUD" },
  { code: "BD", name: "Bangladesh", lang: "bn", currency: "BDT" },
  { code: "IN", name: "India", lang: "hi", currency: "INR" },
  { code: "PK", name: "Pakistan", lang: "en", currency: "PKR" },
  { code: "MX", name: "Mexico", lang: "es", currency: "MXN" },
  { code: "ES", name: "Spain", lang: "es", currency: "EUR" },
  { code: "AR", name: "Argentina", lang: "es", currency: "ARS" },
  { code: "CO", name: "Colombia", lang: "es", currency: "COP" },
  { code: "CL", name: "Chile", lang: "es", currency: "CLP" },
  { code: "FR", name: "France", lang: "fr", currency: "EUR" },
  { code: "DE", name: "Germany", lang: "en", currency: "EUR" },
  { code: "IT", name: "Italy", lang: "en", currency: "EUR" },
  { code: "NL", name: "Netherlands", lang: "en", currency: "EUR" },
  { code: "SA", name: "Saudi Arabia", lang: "ar", currency: "SAR" },
  { code: "AE", name: "United Arab Emirates", lang: "ar", currency: "AED" },
  { code: "EG", name: "Egypt", lang: "ar", currency: "EGP" },
  { code: "CN", name: "China", lang: "zh", currency: "CNY" },
  { code: "TW", name: "Taiwan", lang: "zh", currency: "TWD" },
  { code: "HK", name: "Hong Kong", lang: "zh", currency: "HKD" },
  { code: "SG", name: "Singapore", lang: "zh", currency: "SGD" },
  { code: "JP", name: "Japan", lang: "ja", currency: "JPY" },
  { code: "KR", name: "South Korea", lang: "ko", currency: "KRW" },
  { code: "ID", name: "Indonesia", lang: "id", currency: "IDR" },
  { code: "MY", name: "Malaysia", lang: "en", currency: "MYR" },
  { code: "TH", name: "Thailand", lang: "en", currency: "THB" },
  { code: "VN", name: "Vietnam", lang: "en", currency: "VND" },
  { code: "PH", name: "Philippines", lang: "en", currency: "PHP" },
  { code: "BR", name: "Brazil", lang: "en", currency: "BRL" },
  { code: "RU", name: "Russia", lang: "en", currency: "RUB" },
  { code: "TR", name: "Turkey", lang: "en", currency: "TRY" },
  { code: "NG", name: "Nigeria", lang: "en", currency: "NGN" },
  { code: "ZA", name: "South Africa", lang: "en", currency: "ZAR" },
  { code: "KE", name: "Kenya", lang: "en", currency: "KES" },
];
